### ISSUE TITLE
Can I suggest to change the name?

### ISSUE THREAD

**Issue by tssm** [javier-lopez/sml.vim#10]
Yes, it makes Vim behave like Emacs as described in the course but this plug-in is generic enough to call it something like `sml-runtime.vim` or something else to avoid misleading other SML programmers.

**Comment by javier-lopez** [comment]
I agree, it's become generic enough for general sml programming, therefore I've rename it to sml.vim , thank you for the suggestion!

**Comment by tssm** [comment]
Thanks to you!

**Comment by tssm** [comment]
Thanks to you for the plug-in! Vim defaults are awful 😄
